### ISSUE TITLE
OMVC-1 Dodawanie kategorii do ogłoszenia

### ISSUE THREAD

**Issue by AdamSupinski** [BartoszSiemienczuk/OgloszeniaMVC#1]
Rozszerzyć widok /Ad/Create oraz /Ad/Edit, by umożliwić użytkownikowi dodawanie wielu kategorii do tworzonego ogłoszenia

**Comment by AdamSupinski** [comment]
UPDATE: 
Jeżeli ustawiamy wybraną kategorię dla danego ogłoszenia, powinna ona dziedziczyć zarówno kategorie nadrzędne, jak i podrzędne. 

Przykład: jeżeli wybierzemy "Samochody osobowe" jako kategorię dla ogłoszenia, powinno dodać również Motoryzację.

**Comment by BartoszSiemienczuk** [comment]
chyba nadrzędne? przecież samochod zawsze bedzie motoryzacja, ale nie zawsze zabytkowym samochodem osobowym :)
