### ISSUE TITLE
OMVC-3 Wiadomości od administracji

### ISSUE THREAD

**Issue by AdamSupinski** [BartoszSiemienczuk/OgloszeniaMVC#3]
"Wiadomości od administratora. Administrator może redagować krótkie wiadomości, które będą się pojawiały na stronie głównej serwisu"

1. Utworzenie nowej encji odpowiadającej za wiadomości od administratora (sugerowane pola: id, tytuł, treść, data ważności)
2. Wyświetlenie wiadomości (np. w formie listy) na /Home/Index. Wyświetlanie zależne od daty ważności (ukryte przy jej przekroczeniu)

**Comment by BartoszSiemienczuk** [comment]
Done.
